force-app/main/default/objects/Chit_Customer__c/Chit_Customer__c.object-meta.xml
<CustomObject>
    <label>Chit Customer</label>
    <nameField>
        <label>Customer Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chit Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chit_Groups__c/Chit_Groups__c.object-meta.xml
<CustomObject>
    <label>Chit Group</label>
    <nameField>
        <label>Chit Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chit Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chit_Groups__c/fields/Selected_Chit_Customers__c.field-meta.xml
<CustomField>
    <fullName>Selected_Chit_Customers__c</fullName>
    <label>Selected Chit Customers</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AddEditMultipleCustFlowHandler.cls
public class AddEditMultipleCustFlowHandler {
    
    @InvocableMethod(label='Add / Edit Chit Customers' description='Processing exisisting CC Records' category='Chit_Customer__c')
    Public static List<Results> prepareList(List<Requests> reqList){
        List<string> ccList = new List<string>();
        List<Results> responseWrapper = new List<Results>();
        if(reqList.size()>0 && reqList[0].cgRecord != null && reqList[0].cgRecord.Selected_Chit_Customers__c != null){
           String existingCCIds =  reqList[0].cgRecord.Selected_Chit_Customers__c;
           existingCCIds = existingCCIds.removeEnd(',');
           ccList.addAll(existingCCIds.split(','));
           Results response = new Results();
            response.existingCCIds = ccList;
            responseWrapper.add(response);
        }
        return responseWrapper;
    }
    Public class Requests{
        @InvocableVariable(label = 'Record for Input' description = 'Chit group record Id')
        Public Chit_Groups__c cgRecord;
    }
    Public class Results{
        @InvocableVariable(label = 'Record for Output' description = 'Chit Customer record Id' required = true)
        Public List<string> existingCCIds;
    }
}